homework 20210814
yumashevm/stringconcat-course-clinic pull request #5
Opened 2021-08-18 19:39 UTC by yumashevm

2021-08-31 11:05 UTC, schomework requested changes

2021-08-31 11:05 UTC, schomework commented on README.md
> +[Architecture Kata](https://miro.com/app/board/o9J_l4U4lBI=/)
Неплохо, но можно ещё добавить вывод (хотя он будет и неокончательный)

2021-08-31 11:05 UTC, schomework commented on mainApp/config/detekt/detekt.yml
> +build:
А почему такой огромный конфиг? Обычно если указать buildUponDefaultConfig = true, то нам весь дефолтный конфиг тащить не надо

2021-09-09 13:26 UTC, yumashevm commented on README.md
> +[Architecture Kata](https://miro.com/app/board/o9J_l4U4lBI=/)
А какого плана должны быть выводы? Похоже я не уловил переход от нефункциональных требований к выводам )

2021-09-09 13:27 UTC, yumashevm commented on mainApp/config/detekt/detekt.yml
> +build:
я просто сгенерировал его командой

2021-09-25 16:07 UTC, merged